# define the network of services
services:
    # prefer to name the service provided rather than the technology
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

    app:
        build:
            dockerfile: ./app/Dockerfile
        volumes:
            - ./app:/app