# will be used for development
#docker compose -f docker-compose.dev.yaml up -d

# define the network of services
services:
    # prefer to name the service provided rather than the technology

    # nginx
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

    # php
    app:
        build:
            dockerfile: ./php/Dockerfile
        volumes:
            - ./app:/var/www/html

    # mysql
    db:
        image: mysql:8.0
        volumes:
            - mysqldata:/var/lib/mysql
        ports:
            - "33306:3306"
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_USER: user
            MYSQL_PASSWORD: secret
            MYSQL_DATABASE: docker-php
            
    # redis

volumes:
    mysqldata: